version: "3.9"
services:

  balthasar:
    image: couchbase/server
    volumes:
      - ./couchbase/node1:/opt/couchbase/var

  melchior:
    image: couchbase/server
    volumes:
      - ./couchbase/node2:/opt/couchbase/var

  # Nodo principale con l'interfaccia grafica
  casper:
    image: couchbase/server
    volumes:
      - ./couchbase/node3:/opt/couchbase/var
    ports:
      - 8091:8091 # 8092:8092 8093:8093 11210:11210