version: "3.9"

networks:
  appnet:
    ipam:
      config:
        - subnet: "172.24.2.0/16"

services:
  
  balthasar:
    image: couchbase/server
    volumes:
      - ./couchbase/node1:/opt/couchbase/var
    networks:
      appnet:
        ipv4_address: "172.24.2.3"

  melchior:
    image: couchbase/server
    volumes:
      - ./couchbase/node2:/opt/couchbase/var
    networks:
      appnet:
        ipv4_address: "172.24.2.2"


  # Nodo principale con l'interfaccia grafica
  casper:
    image: couchbase/server
    volumes:
      - ./couchbase/node3:/opt/couchbase/var
    networks:
      appnet:
        ipv4_address: "172.24.2.1"
    ports:
      - 8091:8091 
      - 8092:8092 
      - 8093:8093 
      - 11210:11210